dbfilename redis_queue.rdb
dir /home/arivu/frappe-v16-bench/config/pids
pidfile /home/arivu/frappe-v16-bench/config/pids/redis_queue.pid
bind 127.0.0.1
port 11000

aclfile /home/arivu/frappe-v16-bench/config/redis_queue.acl
